task :default => [:staging]

task :staging do |t|
    run_tests t.name
end

task :production do |t|
    run_tests t.name
end

task :debug do |t|
    # launch the debug webserver here
    run_tests t.name
    # shutdown the debug webserver here
end

def run_tests(env)
    sh "rake -f api_tests.rb default[#{env}]"
end
