task :default => [:staging]

task :staging do
    run_tests "STAGING"
end

task :production do
    run_tests "PRODUCTION"
end

task :debug do
    run_tests "DEBUG"
end

def run_tests(env)
    sh "rake -f api_tests.rb default[#{env}]"
end
